language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add starship ./
  - asdf list-all starship
  - asdf plugin-test starship ./ 'starship help' || exit 1
os:
  - linux
  - osx
