name: Auto assign

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-reviewer:
    if: github.event.pull_request.user.login != 'gr1m0h'
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit "${{ github.event.pull_request.number }}" --add-reviewer gr1m0h --repo "${{ github.repository }}"
