# <target-repo>/.github/workflows/security.yml
name: security
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  osv-scan:
    uses: gr1m0h/.github/.github/workflows/osv-scanner.yml@a1daee3f634d6041820982c83db1e50435ffe708
    permissions:
      contents: read
      security-events: write
  gitleaks:
    uses: gr1m0h/.github/.github/workflows/gitleaks.yml@a1daee3f634d6041820982c83db1e50435ffe708
  dependency-review:
    if: github.event_name == 'pull_request'
    uses: gr1m0h/.github/.github/workflows/dependency-review.yml@a1daee3f634d6041820982c83db1e50435ffe708
    permissions:
      contents: read
      pull-requests: write
  actionlint:
    uses: gr1m0h/.github/.github/workflows/actions-pin-lint.yml@a1daee3f634d6041820982c83db1e50435ffe708
