# <target-repo>/.github/workflows/security.yml
name: security
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  osv-scan:
    uses: gr1m0h/.github/.github/workflows/osv-scanner.yml@be69be10c77cf994a09c725344be196f36e20587
    permissions:
      contents: read
      security-events: write
  gitleaks:
    uses: gr1m0h/.github/.github/workflows/gitleaks.yml@be69be10c77cf994a09c725344be196f36e20587
  dependency-review:
    if: github.event_name == 'pull_request'
    uses: gr1m0h/.github/.github/workflows/dependency-review.yml@be69be10c77cf994a09c725344be196f36e20587
    permissions:
      contents: read
      pull-requests: write
  actionlint:
    uses: gr1m0h/.github/.github/workflows/actions-pin-lint.yml@be69be10c77cf994a09c725344be196f36e20587
